--- #YAML:1.0
name:               Math-StochasticProcess
version:            0.02
abstract:           Stochastic Process
author:
    - Nicholas Bamber <theabbot@silasthemonk.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Params::Validate:  0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
